### ISSUE TITLE
Check inputs for non-unicode chars

### ISSUE THREAD

**Issue by pbca26** [pbca26/komodo-tokens-wallet#6]

**Comment by SirSevenG** [comment]
Can't create tokens with non-unicode chars in name/description/nft data.
Yet, the only error I can see in error message is:
![Screenshot 2021-07-28 at 17-53-17 Komodo Tokens Wallet (v0 1 6)](https://user-images.githubusercontent.com/44422309/127311006-13edb810-3ed6-4bcc-bb5f-20048ab46828.png)

**Comment by SirSevenG** [comment]
Correct error messages are displayed now.

![изображение](https://user-images.githubusercontent.com/44422309/127521500-cb27719b-7402-4a5a-83aa-25d7066aa915.png)

Issue can be closed.
