### ISSUE TITLE
Highlight that tokens not confirmed yet

### ISSUE THREAD

**Issue by tonymorony** [pbca26/komodo-tokens-wallet#8]
Minor one: it's not clear that I can't select tokens because they have not been confirmed yet (e.g. write "(unconfirmed)" near token name)
![image](https://user-images.githubusercontent.com/24797699/126630000-9918c72a-dd39-4c4b-b88b-7bd8a648869f.png)

**Comment by SirSevenG** [comment]
There's clear indication now for unconfirmed tokens.
